language: java

before_install:
  - LOCATION="http://dl.google.com/android/android-sdk_r22.3-linux.tgz"
  - EXPECTED_SHA1="9b7fc38f27e411297f4a183019ea2c10b1148252"
  - wget -O android-sdk-linux.tar.gz ${LOCATION}
  - ACTUAL_SHA1=$(sha1sum android-sdk-linux.tar.gz | cut -f 1 -d ' ')
  - test "${EXPECTED_SHA1}" = "${ACTUAL_SHA1}"
  - tar -xvf android-sdk-linux.tar.gz
  - export ANDROID_HOME=android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - SUPPORT_REPO_NUM=$(android list sdk --no-ui | grep "Android Support Repository" | cut -f 1 -d '-')
  - PLATFORM_TOOLS_NUM=$(android list sdk --no-ui | grep "Android SDK Platform-tools" | cut -f 1 -d '-')
  - SDK_NUM=$(android list sdk --no-ui | grep ", API 19," | cut -f 1 -d '-')
  - echo "y" | android update sdk --filter "${SUPPORT_REPO_NUM}" --no-ui --force
  - echo "y" | android update sdk --filter "${PLATFORM_TOOLS_NUM}" --no-ui --force
  - echo "y" | android update sdk --filter "${SDK_NUM}" --no-ui --force

