language: java

before_install:
  - LOCATION="http://dl.google.com/android/android-sdk_r22.3-linux.tgz"
  - EXPECTED_SHA1="9b7fc38f27e411297f4a183019ea2c10b1148252"
  - wget -O android-sdk-linux.tar.gz ${LOCATION}
  - ACTUAL_SHA1=$(sha1sum android-sdk-linux.tar.gz | cut -f 1 -d ' ')
  - test "${EXPECTED_SHA1}" = "${ACTUAL_SHA1}"
  - tar -xvf android-sdk-linux.tar.gz
  - export ANDROID_HOME=android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - sudo apt-get install -q libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386
  - echo "y" | android update sdk --no-ui -a --filter extra-android-m2repository,build-tools-19.0.0,platform-tools,android-19

